[tool.black]
line-length = 88
target-version = ['py38', 'py39', 'py310']
include = '\.pyi?$'  # Solo archivos .py y .pyi
exclude = '''
/(
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | migrations
    | env
    | venv
    | DjangoPet
)/
'''
src = ["DjangoPet"]