# Generated by Django 4.2.20 on 2025-04-02 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mascota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("especie", models.CharField(max_length=50)),
                ("raza", models.CharField(max_length=100)),
                (
                    "genero",
                    models.CharField(
                        choices=[("Macho", "Macho"), ("Hembra", "Hembra")],
                        max_length=10,
                    ),
                ),
                ("color", models.CharField(max_length=50)),
                ("peso", models.DecimalField(decimal_places=2, max_digits=5)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="mascotas/"),
                ),
                ("esterilizado", models.BooleanField(default=False)),
                (
                    "numero_microchip",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("fecha_ultimo_control", models.DateField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ACTIVO", "Activo"),
                            ("FALLECIDO", "Fallecido"),
                            ("EN_TRATAMIENTO", "En Tratamiento"),
                        ],
                        default="ACTIVO",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "propietario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mascotas",
                        to="users.propietario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FichaMedica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_ficha",
                    models.PositiveIntegerField(editable=False, unique=True),
                ),
                ("descripcion", models.TextField()),
                ("alergias", models.TextField(blank=True)),
                ("vacunas", models.TextField(max_length=255)),
                ("desparasitado", models.BooleanField(default=False)),
                ("fecha_desparasitacion", models.DateField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mascota",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ficha_medica",
                        to="pets.mascota",
                    ),
                ),
            ],
        ),
    ]
