# Generated by Django 4.2.20 on 2025-04-02 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pets", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_consulta", models.DateTimeField()),
                (
                    "duracion",
                    models.IntegerField(default=30, help_text="Duración en minutos"),
                ),
                (
                    "estado_cita",
                    models.CharField(
                        choices=[
                            ("ACTIVA", "Activa"),
                            ("CANCELADA", "Cancelada"),
                            ("REPROGRAMADA", "Reprogramada"),
                            ("COMPLETADA", "Completada"),
                        ],
                        default="ACTIVA",
                        max_length=15,
                    ),
                ),
                ("motivo", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("diagnostico", models.TextField(blank=True, null=True)),
                (
                    "temperatura",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "unidad_temperatura",
                    models.CharField(
                        choices=[("C", "Celsius"), ("F", "Fahrenheit")],
                        default="C",
                        max_length=1,
                    ),
                ),
                (
                    "peso",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "unidad_peso",
                    models.CharField(
                        choices=[("KG", "Kilogramos"), ("LB", "Libras")],
                        default="KG",
                        max_length=2,
                    ),
                ),
                ("notas_internas", models.TextField(blank=True)),
                (
                    "costo_consulta",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("requiere_control", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mascota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultas",
                        to="pets.mascota",
                    ),
                ),
                (
                    "veterinario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultas",
                        to="users.veterinario",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
